[package]
name = "FicsItNetworksDocumentationCLI"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2.21"
serde = { version = "1.0.204", features = ["derive"] }
serde_with = "3.9.0"
serde_json = "1.0.120"
regex = "1.10.5"
indoc = "2.0.5"
toml = "0.8.16"