name: Deploy to SMR

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SMR_API_KEY:
        required: true
      RELEASE_WEBHOOK_URL:
        required: true

permissions:
  actions: read
  contents: write

jobs:
  deploy-to-smr:
    name: Deploy to SMR
    runs-on: ubuntu-latest
    steps:
      - name: Find Release
        uses: actions/github-script@v7
        id: find-release
        with:
          script: |
            const response = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            const release = response.data[0];
            if (release.draft) {
              core.setFailed('Found Release is a draft!');
              return;
            }
            return {body: release.body, body_encoded: btoa(release.body), tag_name: release.tag_name, name: release.name};
      
      - name: Download FicsIt-Networks Version
        uses: robinraju/release-downloader@v1.11
        with:
          latest: true
          fileName: "FicsItNetworks.zip"

      - name: Upload to SMR
        run: |
          VAR_ENCODED="${{ steps.find-release.outputs.result.body_encoded }}"
          VAR=$(echo "$VAR_ENCODED" | base64 --decode)
          ./ficsit-cli --api-key "${{secrets.SMR_API_KEY}}" smr upload FicsItNetworks FicsItNetworks.zip $VAR

      - name: Wait for Approval
        uses: actions/github-script@v7
        with:
          script: |
            while (true) {
              let response = await fetch("https://api.ficsit.app/v2/query", {
                headers: {"Cookies": "token=${{secrets.SMR_API_TOKEN}}"},
                body: '{getModByReference(modReference:"FicsItNetworks"){versions(filter:{order_by:created_at}){approved}}}'
              })
              if (!response.ok) {
                console.log(`Checking Fetch: Response is not OK: ${response.status}`; 
              } else {
                const json = await response.json();
                let mod = json.data.getModByReference[0];
                if (mod.approved && mod.virustotal_results.safe) {
                  console.log("Version got approved!");
                  return;
                }
                console.log("Version not approved yet");
              }
              await sleep(5 * 1000);
            }
  send-discord-release-message:
    needs: deploy-to-smr
    uses: ./.github/workflows/send-discord-release.yml
    secrets:
      RELEASE_WEBHOOK_URL: ${{ secrets.RELEASE_WEBHOOK_URL }}