name: Generate Documentation

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Find FicsIt-Networks Binary
        uses: actions/github-script@v7
        id: find-ficsit-networks
        with:
          script: |
            const response = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
              name: "FicsItNetworks"
            });
            return response.data.artifacts[0].workflow_run.id;

      - name: Download SML
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "satisfactorymodding/SatisfactoryModLoader"
          latest: true
          fileName: "SML-LinuxServer.zip"

      - name: Download FicsIt-Networks
        uses: actions/download-artifact@v4
        with:
          name: FicsItNetworks
          run-id: ${{ steps.find-ficsit-networks.outputs.result }}
          path: ${{ github.workspace }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Download Satisfactroy Dedicated Server
        run: |
          steamcmd +force_install_dir "${{ github.workspace }}/SatisfactoryDedicatedServer" +login anonymous +app_update 1690800 validate +quit
      
      - name: Install FicsIt-Networks & SML
        run: |
          mkdir SatisfactoryDedicatedServer/FactoryGame/Mods
          unzip FicsItNetworks-LinuxServer.zip -d SatisfactoryDedicatedServer/FactoryGame/Mods/FicsItNetworks
          unzip SML-LinuxServer.zip -d SatisfactoryDedicatedServer/FactoryGame/Mods/SML
      
      - name: Generate Documentation
        working-directory: SatisfactoryDedicatedServer
        run: ./FactoryServer.sh -FINGenDocAndQuit
      
      - name: Upload Documentation
        id: upload-documentation
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: |
            ~/.config/Epic/FactoryGame/Saved/FINDocumentation.json
            ~/.config/Epic/FactoryGame/Saved/FINLuaDocumentation.lua
