name: Generate Documentation

on:
  push:
    branches:
      - development
    paths:
      - ".github/workflows/gen-docs.yml"
      - "FicsItNetworks.uplugin"
      - "Content/**"
      - "Source/**"
      - "ThirdParty/**"

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Find FicsIt-Networks Binary
        uses: actions/github-script@v7
        id: find-ficsit-networks
        with:
          result-encoding: number
          script: |
            const artifacts = github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
              name: "FicsItNetworks-Windows"
            });
            console.log(artifacts);
            return artifacts.artifacts[0].workflow_run.id;

      - name: Download FicsIt-Networks
        uses: actions/download-artifact@v4
        with:
          name: FicsItNetworks
          run-id: ${{ steps.find-ficsit-networks.outputs.result }}
          path: ${{ github.workspace }}

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Download Satisfactroy Dedicated Server
        run: |
          steamcmd +force_install_dir "${{ github.workspace }}/SatisfactoryDedicatedServer" +login anonymous +app_update 1690800 validate +quit
      
      - name: Install FicsIt-Networks
        run: |
          unzip FicsItNetworks-LinuxServer.zip -d SatisfactoryDedicatedServer/FactoryGame/Mods/FicsItNetworks
      
      - name: Generate Documentation
        working-directory: SatisfactoryDedicatedServer
        run: ./FactoryServer.sh -FINGenDocAndQuit
      
      - name: Upload Documentation
        id: upload-documentation
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: |
            ~/.config/Epic/FactoryGame/Saved/FINReflectionDocumentation.json
            ~/.config/Epic/FactoryGame/Saved/FINLuaDocumentation.lua
