name: Update Documentation

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        required: true
        type: string
        default: "FicsItNetworks"
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string

permissions:
  actions: read

jobs:
  update-docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
