name: Update Documentation

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: read

jobs:
  update-docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
